// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for SociaalReceiverFunction
 */
export interface SociaalReceiverFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/submission-processor/sociaal-receiver-lambda/sociaal-receiver.
 */
export class SociaalReceiverFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: SociaalReceiverFunctionProps) {
    super(scope, id, {
      description: 'src/submission-processor/sociaal-receiver-lambda/sociaal-receiver.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/submission-processor/sociaal-receiver-lambda/sociaal-receiver.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}